In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Min-Max normalization function
def normalize(data):
    return (data - np.min(data)) / (np.max(data) - np.min(data))

# Initialize input data and true labels
X1 = np.array([1, 2, 3])
X2 = np.array([3, 4, 5])
# Generate Y_true using the specified function
def generate_y_true(X1, X2):
    return 0.25 * X1**2 + 0.2 * X1 * X2 + 5
Y_true = generate_y_true(X1, X2)
## Plot model of Y_true Generate data points for the 3D plot
X1_plot = np.linspace(np.min(X1), np.max(X1), 100)
X2_plot = np.linspace(np.min(X2), np.max(X2), 100)
X1_plot, X2_plot = np.meshgrid(X1_plot, X2_plot)
Y_true_plot = generate_y_true(X1_plot, X2_plot)

# Plotting Y_true as a function of X1 and X2
fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(X1_plot, X2_plot, Y_true_plot, cmap='viridis', alpha=0.7)
ax.set_xlabel('X1')
ax.set_ylabel('X2')
ax.set_zlabel('Y_true')
ax.set_title('Y_true as a Function of X1 and X2')

plt.show()



# Normalize inputs and outputs
X1_normalized = normalize(X1)
X2_normalized = normalize(X2)
Y_true_normalized = normalize(Y_true)

# Initialize weights and biases
np.random.seed(42)
W11, W21, W12, W22 = 2 * np.random.rand(4) - 1
W31, W41, W32, W42 = 2 * np.random.rand(4) - 1
w51, w52 = 2 * np.random.rand(2) - 1
b1, b2, b3, b4 = 2 * np.random.rand(4) - 1


np.random.seed(42)
W11, W21, W12, W22 = 2 * np.random.rand(4) - 1 
W31, W41, W32, W42 = 2 * np.random.rand(4) - 1
W51, W52 = 2 * np.random.rand(2) - 1
b1, b2, b3, b4 = 2 * np.random.rand(4) - 1






# Hyperparameters
learning_rate = 0.01
epochs = 1

# Lists to store weights for visualization
weights = [W11, W21, W12, W22, W31, W41, W32, W42, w51, w52]
biases = [b1, b2, b3, b4]

# Lists to store weight and bias histories for visualization
weights_history = [[] for _ in range(len(weights))]
biases_history = [[] for _ in range(len(biases))]

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Training the neural network using backpropagation
for epoch in range(epochs):
    # Forward pass
    A11 = sigmoid(X1_normalized * W11 + X2_normalized * W21 + b1)
    A12 = sigmoid(X1_normalized * W12 + X2_normalized * W22 + b2)
    A21 = sigmoid(A11 * W31 + A12 * W41 + b3)
    A22 = sigmoid(A11 * W32 + A12 * W42 + b4)
    Y_pred = A21 * w51 + A22 * w52

    # Calculate the loss
    loss = np.mean((Y_pred - Y_true_normalized)**2)

    # Backward pass
    d_loss = 2 * (Y_pred - Y_true_normalized) / len(Y_true_normalized)
    d_w51 = A21 * d_loss
    d_w52 = A22 * d_loss

    d_A21 = w51 * d_loss
    d_A22 = w52 * d_loss

    d_A11 = W31 * sigmoid_derivative(A11) * d_A21
    d_A12 = W41 * sigmoid_derivative(A12) * d_A21

    d_W11 = X1_normalized * sigmoid_derivative(A11) * d_A11
    d_W21 = X2_normalized * sigmoid_derivative(A11) * d_A11
    d_b1 = sigmoid_derivative(A11) * d_A11

    d_W12 = X1_normalized * sigmoid_derivative(A12) * d_A12
    d_W22 = X2_normalized * sigmoid_derivative(A12) * d_A12
    d_b2 = sigmoid_derivative(A12) * d_A12

    d_W31 = A11 * sigmoid_derivative(A21) * d_A21
    d_W41 = A12 * sigmoid_derivative(A21) * d_A21
    d_b3 = sigmoid_derivative(A21) * d_A21

    d_W32 = A11 * sigmoid_derivative(A22) * d_A22
    d_W42 = A12 * sigmoid_derivative(A22) * d_A22
    d_b4 = sigmoid_derivative(A22) * d_A22

    # Update weights and biases
    w51 -= learning_rate * np.mean(d_w51)
    w52 -= learning_rate * np.mean(d_w52)

    W11 -= learning_rate * np.mean(d_W11)
    W21 -= learning_rate * np.mean(d_W21)
    b1 -= learning_rate * np.mean(d_b1)

    W12 -= learning_rate * np.mean(d_W12)
    W22 -= learning_rate * np.mean(d_W22)
    b2 -= learning_rate * np.mean(d_b2)

    W31 -= learning_rate * np.mean(d_W31)
    W41 -= learning_rate * np.mean(d_W41)
    b3 -= learning_rate * np.mean(d_b3)

    W32 -= learning_rate * np.mean(d_W32)
    W42 -= learning_rate * np.mean(d_W42)
    b4 -= learning_rate * np.mean(d_b4)

    # Update the weights list
    weights = [W11, W21, W12, W22, W31, W41, W32, W42, w51, w52]

    # Append weights and biases for visualization
    for i, weight in enumerate(weights):
        weights_history[i].append(weight)

    for i, bias in enumerate(biases):
        biases_history[i].append(bias)

# Plotting the weights over iterations
fig, axes = plt.subplots(len(weights_history) + len(biases_history), 1, figsize=(10, 20))

for i, weight_history in enumerate(weights_history):
    axes[i].plot(weight_history)
    axes[i].set_title(f'Weight {i+1}')

for i, bias_history in enumerate(biases_history):
    axes[len(weights_history) + i].plot(bias_history)
    axes[len(weights_history) + i].set_title(f'Bias {i+1}')

plt.tight_layout()
plt.show()


In [9]:
d_loss

array([ 0.18521405, -0.08408282, -0.49059836])

In [7]:
d_w51/2

array([ 0.04582936, -0.01985686, -0.11048428])

In [8]:
A21

array([0.49487992, 0.4723167 , 0.45040622])

In [10]:
Y_pred

array([0.27782107, 0.27160304, 0.26410246])

In [13]:
X1_normalized * W11 + X2_normalized * W21 + b1

array([-0.95884313, -0.63360326, -0.3083634 ])

In [14]:
X1_normalized

array([0. , 0.5, 1. ])

In [15]:
X2_normalized

array([0. , 0.5, 1. ])

In [16]:
W21

0.9014140502679847

In [17]:
W11

-0.2509343248571227

In [18]:
# Normalize inputs and outputs
X1_normalized = normalize(X1)
X2_normalized = normalize(X2)
Y_true_normalized = normalize(Y_true)

# Initialize weights and biases
np.random.seed(42)
W11, W21, W12, W22 = 2 * np.random.rand(4) - 1
W31, W41, W32, W42 = 2 * np.random.rand(4) - 1
w51, w52 = 2 * np.random.rand(2) - 1
b1, b2, b3, b4 = 2 * np.random.rand(4) - 1

In [28]:
    A11 = sigmoid(X1_normalized * W11 + X2_normalized * W21 + b1)
    A12 = sigmoid(X1_normalized * W12 + X2_normalized * W22 + b2)
    A21 = sigmoid(A11 * W31 + A12 * W41 + b3)
    A22 = sigmoid(A11 * W32 + A12 * W42 + b4)
    Y_pred = A21 * w51 + A22 * w52

In [36]:
X1_normalized * W11 + X2_normalized * W21 + b1

array([-0.95883101, -0.63357659, -0.30832216])

In [32]:
X1_normalized

array([0. , 0.5, 1. ])

In [33]:
X2_normalized

array([0. , 0.5, 1. ])

In [34]:
W11

-0.250919762305275

In [35]:
W21

0.9014286128198323